language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
  - gem install bundler
  - bundle config --local build.sassc --disable-march-tune-native
script:
  - bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: gh-pages
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master